# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r:
- 3.4
- 3.5
- 3.6
- oldrel
- release
- devel

before_install:
  - pip install --user h5py tensorflow

after_success:
  - Rscript -e 'covr::codecov()'
