# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.3
- release

before_script:
  - pip install h5py
after_success:
  - Rscript -e 'covr::codecov()'
