# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- 3.3
- release

before_script:
  - Rscript -e 'reticulate::install_tensorflow()'

after_success:
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      - python2.7
      - python-numpy
      - python-scipy
      - python-h5py
